<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Time;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $nome varchar(255) NOT NULL
 * @property mixed $sigla varchar(255) NOT NULL
 * @property mixed $path varchar(255) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $updated datetime NOT NULL
 */
trait TimeFields
{
}
