<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Local;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $nome varchar(255) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $updated datetime NOT NULL
 */
class LocalRow extends Row
{
    protected $cols = [
        'id' => null,
        'nome' => null,
        'created' => null,
        'updated' => null,
    ];
}
