<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Jogo;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $local int(10,0) NOT NULL
 * @property mixed $horario datetime NOT NULL
 * @property mixed $mandante int(10,0) NOT NULL
 * @property mixed $visitante int(10,0) NOT NULL
 * @property mixed $descricao varchar(255) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $updated datetime NOT NULL
 */
trait JogoFields
{
}
