<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Jogo;

use Atlas\Table\Table;

/**
 * @method JogoRow|null fetchRow($primaryVal)
 * @method JogoRow[] fetchRows(array $primaryVals)
 * @method JogoTableSelect select(array $whereEquals = [])
 * @method JogoRow newRow(array $cols = [])
 * @method JogoRow newSelectedRow(array $cols)
 */
class JogoTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'jogos';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'local' => array (
  'name' => 'local',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'horario' => array (
  'name' => 'horario',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'mandante' => array (
  'name' => 'mandante',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'visitante' => array (
  'name' => 'visitante',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'descricao' => array (
    'name' => 'descricao',
    'type' => 'varchar',
    'size' => 255,
    'scale' => NULL,
    'notnull' => true,
    'default' => NULL,
    'autoinc' => false,
    'primary' => false,
    'options' => NULL,
  ),
        'created' => array (
  'name' => 'created',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated' => array (
  'name' => 'updated',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'local',
        'horario',
        'mandante',
        'visitante',
        'descricao',
        'created',
        'updated',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'local' => null,
        'horario' => null,
        'mandante' => null,
        'visitante' => null,
        'descricao' => null,
        'created' => null,
        'updated' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
